version: "3.9"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: temporal
      POSTGRES_PASSWORD: temporal
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U temporal"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  temporal:
    image: temporalio/auto-setup:1.22.3
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "7233:7233"
    environment:
      DB: postgresql
      POSTGRES_DB: temporal
      DB_PORT: 5432
      POSTGRES_USER: temporal
      POSTGRES_PWD: temporal
      POSTGRES_SEEDS: postgres
    networks:
      - default

  fastapi:
    build: .
    depends_on:
      temporal:
        condition: service_started
    networks:
      - default
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build: .
    depends_on:
      temporal:
        condition: service_started
    networks:
      - default
    command: python worker.py

networks:
  default: